### ISSUE TITLE
void com.github.pedrovgs.nox.NoxItemCatalog.addObserver(java.util.Observer)

### ISSUE THREAD

**Issue by Millerscript** [Karumi/HeaderRecyclerView#19]
05-23 10:01:05.258 31803-31803/com.karumi.headerrecyclerview E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.karumi.headerrecyclerview, PID: 31803
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.pedrovgs.nox.NoxItemCatalog.addObserver(java.util.Observer)' on a null object reference
                                                                                   at com.github.pedrovgs.nox.NoxView.resume(NoxView.java:267)
                                                                                   at com.github.pedrovgs.nox.NoxView.onVisibilityChanged(NoxView.java:239)
                                                                                   at android.view.View.dispatchAttachedToWindow(View.java:14553)
                                                                                   at android.view.ViewGroup.addViewInner(ViewGroup.java:4351)
                                                                                   at android.view.ViewGroup.addView(ViewGroup.java:4148)
                                                                                   at android.view.ViewGroup.addView(ViewGroup.java:4089)
                                                                                   at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:711)
                                                                                   at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
                                                                                   at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7877)
                                                                                   at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7835)
                                                                                   at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7823)
                                                                                   at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:579)
                                                                                   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                                   at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                                   at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                                   at android.view.View.layout(View.java:16646)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                   at android.view.View.layout(View.java:16646)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                   at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                                                                                   at android.view.View.layout(View.java:16646)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                   at android.view.View.layout(View.java:16646)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                   at android.view.View.layout(View.java:16646)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                   at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                                   at android.view.View.layout(View.java:16646)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                                   at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
                                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1943)
                                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
                                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
                                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                   at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                   at android.os.Handler.handleCallback(Handler.java:746)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by pedrovgs** [comment]
Hi @Millerscript, thanks for reporting the issue. This error seems to be related to the library we are using in the project example. We are going to report it to the official lib repository and close this issue, as there is no a quick workaround we can't fix the error changing our code. Thanks!
